import type { Lang, PortfolioContent } from "./types";

export const PORTFOLIO_CONTENT: Record<Lang, PortfolioContent> = {
  es: {
    nav: {
      work: "Trabajo",
      about: "Sobre mí",
      process: "Proceso",
      stack: "Stack",
      credentials: "Formación",
      contact: "Contacto",
      cv: "Descargar CV",
      hire: "Contactarme",
    },
    hero: {
      eyebrow: "Disponible · Full-time · Freelance · Remoto",
      name: ["Maximiliano", "Aramayo"],
      tagline: "Fullstack Engineer.",
      tagline2: "Construyo sistemas reales — de la idea al deploy.",
      sub: "Ingeniero en Informática. React · TypeScript · Node.js. Cubro relevamiento, arquitectura, desarrollo, integración y deploy. Productos en producción en salud, servicios y retail.",
      ctaPrimary: "Ver proyectos",
      ctaSecondary: "Descargar CV",
      meta: {
        based: "Basado en Argentina",
        timezone: "GMT-3 · Trabajo remoto global",
        years: "2+ años construyendo en producción",
      },
    },
    metrics: [
      { value: "3", label: "Productos en producción", note: "Salud · Retail · Automatización" },
      { value: "10+", label: "Proyectos entregados", note: "End-to-end, del análisis al deploy" },
      { value: "80%", label: "Reducción tiempo informes", note: "Caso: gestión médica" },
      { value: "24/7", label: "Portal pacientes", note: "0 documentos perdidos" },
    ],
    about: {
      eyebrow: "Sobre mí",
      title: "Construyo software con criterio de ingeniería y mirada de negocio.",
      body1: "Soy Ingeniero en Informática con base en Administración de Empresas. No vengo de una trayectoria corporativa larga — vengo de construir productos reales, completos, en producción, con usuarios pagos del otro lado.",
      body2: "Mi enfoque es end-to-end: empiezo escuchando el problema, modelo el dominio, defino arquitectura, escribo el código, integro lo que haga falta y lo dejo corriendo. Pongo el mismo cuidado en una query como en una conversación con el cliente.",
      body3: "Trabajo en proyectos de salud, servicios y retail. Me interesa el código mantenible, la seguridad razonable y las decisiones que se sostienen seis meses después.",
      photoCaption: "Maximiliano Aramayo Lazo — Buenos Aires, AR",
    },
    work: {
      eyebrow: "Trabajo seleccionado",
      title: "Tres productos, un patrón: problema real, solución medible.",
      sub: "Resumen ejecutivo. Cada proyecto se expande con arquitectura, decisiones técnicas, desafíos e impacto.",
      seeAll: "Ver todos los proyectos",
      expand: "Ver caso",
      readCase: "Leer case study completo",
    },
    process: {
      eyebrow: "Cómo trabajo",
      title: "Un proceso simple, sostenido por criterio.",
      steps: [
        { n: "01", t: "Relevamiento", d: "Entiendo el negocio, las restricciones y a quién le duele el problema. Documento antes de codear." },
        { n: "02", t: "Modelado", d: "Diseño dominio, datos y flujos. Diagramas si suman; conversaciones si son más rápidas." },
        { n: "03", t: "Arquitectura", d: "Defino stack, separación de responsabilidades, contratos. SOLID donde paga; pragmatismo donde no." },
        { n: "04", t: "Desarrollo", d: "Itero en sprints cortos con entregables visibles. TypeScript de punta a punta cuando aplica." },
        { n: "05", t: "Integración", d: "APIs externas, pasarelas de pago, IA aplicada, automatizaciones. Lo que el producto necesita." },
        { n: "06", t: "Deploy & soporte", d: "CI/CD, observabilidad razonable, handoff o mantenimiento continuo. El proyecto vive después." },
      ],
    },
    stack: {
      eyebrow: "Stack",
      title: "Herramientas que uso a diario en producción.",
      groups: [
        { k: "Frontend", v: ["React", "Next.js", "Angular", "TypeScript", "Tailwind"] },
        { k: "Backend", v: ["Node.js", "NestJS", "Express", "Prisma", "REST APIs", "JWT"] },
        { k: "Bases de datos", v: ["PostgreSQL", "Firebase", "Firestore", "SQL"] },
        { k: "Infra & Cloud", v: ["Vercel", "Render", "Google Cloud", "AWS S3", "Docker", "GitHub"] },
        { k: "Automatización", v: ["n8n", "WhatsApp Business API", "MercadoPago", "Google Sheets API"] },
        { k: "IA aplicada", v: ["Claude Code", "OpenAI Codex", "GitHub Copilot"] },
        { k: "Método", v: ["Scrum", "Kanban", "SDLC", "UML", "Clean Architecture", "SOLID"] },
      ],
    },
    credentials: {
      eyebrow: "Formación & Credenciales",
      title: "Fundamentos formales detrás de los productos.",
      sub: "El núcleo del portfolio son proyectos e impacto. Esto refuerza la base.",
      items: [
        {
          type: "Título",
          name: "Ingeniería en Informática",
          issuer: "Universidad",
          year: "2026",
          status: "Emitido",
          note: "Graduado 2025 · Título emitido 2026. Fundamentos de software, arquitectura, bases de datos, redes y gestión de proyectos.",
          image: "/imagenes-perfil/Certificado-ING.jpeg",
        },
        {
          type: "Certificación",
          name: "Claude Code in Action",
          issuer: "Anthropic",
          year: "2026",
          status: "Verificado",
          note: "Desarrollo asistido por IA en flujos de trabajo de ingeniería real.",
          image: "/imagenes-perfil/certificado de claude.png",
        },
      ],
      addMore: "Espacio reservado para futuras certificaciones.",
    },
    availability: {
      eyebrow: "Disponibilidad",
      title: "Abierto a proyectos serios.",
      modes: [
        { k: "Full-time", d: "Roles fullstack senior. Producto, scale-up, agencia." },
        { k: "Freelance", d: "Proyectos cerrados con entregables claros. NDA si corresponde." },
        { k: "Consultoría", d: "Arquitectura, code review, segunda opinión técnica." },
        { k: "Colaboración", d: "Co-fundación o equity para productos con tracción." },
      ],
      location: "Remoto global · Híbrido · Presencial Buenos Aires",
    },
    contact: {
      eyebrow: "Contacto",
      title: "¿Tenés un problema que vale la pena resolver?",
      sub: "Respondo en menos de 24 hs hábiles. Cuanto más concreto el contexto, más rápido te digo si encaja.",
      email: "maxilazo888@gmail.com",
      writeMe: "Escribime",
      copy: "Copiar email",
      copied: "¡Copiado!",
      cv: "CV en PDF",
    },
    footer: {
      colofon: "Diseñado y desarrollado por Maximiliano Aramayo Lazo. Buenos Aires, AR.",
      year: "© 2026",
      built: "Construido con Astro · TypeScript · cuidado.",
    },
    drawer: {
      summary: "Resumen ejecutivo",
      problem: "Problema",
      solution: "Solución",
      stack: "Stack",
      role: "Rol",
      impact: "Impacto",
      status: "Estado",
      readMore: "Leer case study completo",
      close: "Cerrar",
    },
  },

  en: {
    nav: {
      work: "Work",
      about: "About",
      process: "Process",
      stack: "Stack",
      credentials: "Credentials",
      contact: "Contact",
      cv: "Download CV",
      hire: "Get in touch",
    },
    hero: {
      eyebrow: "Available · Full-time · Freelance · Remote",
      name: ["Maximiliano", "Aramayo"],
      tagline: "Fullstack Engineer.",
      tagline2: "I build real systems — from idea to deploy.",
      sub: "Software Engineer. React · TypeScript · Node.js. I handle discovery, architecture, development, integration and deploy. Live products in healthcare, services and retail.",
      ctaPrimary: "View work",
      ctaSecondary: "Download CV",
      meta: {
        based: "Based in Argentina",
        timezone: "GMT-3 · Working globally",
        years: "2+ years shipping to production",
      },
    },
    metrics: [
      { value: "3", label: "Live products", note: "Healthcare · Retail · Automation" },
      { value: "10+", label: "Projects shipped", note: "End-to-end, discovery to deploy" },
      { value: "80%", label: "Faster medical reports", note: "Case: clinical management" },
      { value: "24/7", label: "Patient portal", note: "0 documents lost" },
    ],
    about: {
      eyebrow: "About",
      title: "I build software with engineering judgment and a business lens.",
      body1: "I'm a Software Engineer with a foundation in Business Administration. I haven't spent ten years inside a Fortune 500 — I've spent the last few building real, complete products in production, with paying users on the other side.",
      body2: "My approach is end-to-end: I start by listening to the problem, model the domain, define the architecture, write the code, integrate whatever's needed and ship it running. I put the same care into a SQL query as into a client conversation.",
      body3: "I work across healthcare, services and retail. I care about maintainable code, reasonable security and decisions that still make sense six months later.",
      photoCaption: "Maximiliano Aramayo Lazo — Buenos Aires, AR",
    },
    work: {
      eyebrow: "Selected work",
      title: "Three products, one pattern: real problem, measurable solution.",
      sub: "Executive summary. Each project expands into architecture, technical decisions, challenges and impact.",
      seeAll: "View all projects",
      expand: "View case",
      readCase: "Read full case study",
    },
    process: {
      eyebrow: "How I work",
      title: "A simple process, held up by judgment.",
      steps: [
        { n: "01", t: "Discovery", d: "I understand the business, the constraints and who actually feels the pain. I document before I code." },
        { n: "02", t: "Modeling", d: "I design the domain, data and flows. Diagrams when they help; conversations when they're faster." },
        { n: "03", t: "Architecture", d: "I define stack, separation of concerns, contracts. SOLID where it pays; pragmatism where it doesn't." },
        { n: "04", t: "Development", d: "Short sprints with visible deliverables. End-to-end TypeScript when it fits." },
        { n: "05", t: "Integration", d: "External APIs, payment gateways, applied AI, automation. Whatever the product needs." },
        { n: "06", t: "Deploy & support", d: "CI/CD, reasonable observability, handoff or continuous maintenance. The project lives after launch." },
      ],
    },
    stack: {
      eyebrow: "Stack",
      title: "Tools I use in production, daily.",
      groups: [
        { k: "Frontend", v: ["React", "Next.js", "Angular", "TypeScript", "Tailwind"] },
        { k: "Backend", v: ["Node.js", "NestJS", "Express", "Prisma", "REST APIs", "JWT"] },
        { k: "Databases", v: ["PostgreSQL", "Firebase", "Firestore", "SQL"] },
        { k: "Infra & Cloud", v: ["Vercel", "Render", "Google Cloud", "AWS S3", "Docker", "GitHub"] },
        { k: "Automation", v: ["n8n", "WhatsApp Business API", "MercadoPago", "Google Sheets API"] },
        { k: "Applied AI", v: ["Claude Code", "OpenAI Codex", "GitHub Copilot"] },
        { k: "Method", v: ["Scrum", "Kanban", "SDLC", "UML", "Clean Architecture", "SOLID"] },
      ],
    },
    credentials: {
      eyebrow: "Credentials & Education",
      title: "The formal foundation behind the products.",
      sub: "Projects and impact are the core of this portfolio. This reinforces the base.",
      items: [
        {
          type: "Degree",
          name: "B.Eng. in Computer Science",
          issuer: "University",
          year: "2026",
          status: "Awarded",
          note: "Graduated 2025 · Degree issued 2026. Software foundations, architecture, databases, networks and project management.",
          image: "/imagenes-perfil/Certificado-ING.jpeg",
        },
        {
          type: "Certification",
          name: "Claude Code in Action",
          issuer: "Anthropic",
          year: "2026",
          status: "Verified",
          note: "AI-assisted development applied to real engineering workflows.",
          image: "/imagenes-perfil/certificado de claude.png",
        },
      ],
      addMore: "Reserved space for future certifications.",
    },
    availability: {
      eyebrow: "Availability",
      title: "Open to serious projects.",
      modes: [
        { k: "Full-time", d: "Senior fullstack roles. Product, scale-up, agency." },
        { k: "Freelance", d: "Scoped projects with clear deliverables. NDA when required." },
        { k: "Consulting", d: "Architecture, code review, second technical opinion." },
        { k: "Collaboration", d: "Co-founding or equity for products with traction." },
      ],
      location: "Global remote · Hybrid · On-site Buenos Aires",
    },
    contact: {
      eyebrow: "Contact",
      title: "Got a problem worth solving?",
      sub: "I reply within 24 working hours. The more concrete the context, the faster I can tell you if it fits.",
      email: "maxilazo888@gmail.com",
      writeMe: "Write me",
      copy: "Copy email",
      copied: "Copied!",
      cv: "CV in PDF",
    },
    footer: {
      colofon: "Designed and built by Maximiliano Aramayo Lazo. Buenos Aires, AR.",
      year: "© 2026",
      built: "Built with Astro · TypeScript · care.",
    },
    drawer: {
      summary: "Executive summary",
      problem: "Problem",
      solution: "Solution",
      stack: "Stack",
      role: "Role",
      impact: "Impact",
      status: "Status",
      readMore: "Read full case study",
      close: "Close",
    },
  },
};

export function pick<T extends string | { es: string; en: string }>(
  obj: T | null | undefined,
  lang: Lang
): string {
  if (obj == null) return "";
  if (typeof obj === "string") return obj;
  return obj[lang] ?? obj.es ?? obj.en ?? "";
}
